# Generated by Django 3.0.4 on 2020-03-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200310_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_of_booking',
        ),
        migrations.AddField(
            model_name='booking',
            name='time_of_booking',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
