# Generated by Django 3.0.4 on 2020-03-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200310_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_of_booking',
            field=models.DateTimeField(),
        ),
    ]
