# Generated by Django 3.0.4 on 2020-03-13 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200313_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time_of_booking',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_done_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='date_of_booking',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='booking',
            name='ending_time',
            field=models.TimeField(default=datetime.time),
        ),
        migrations.AddField(
            model_name='booking',
            name='starting_time',
            field=models.TimeField(default=datetime.time),
        ),
    ]
