# Generated by Django 3.0.4 on 2020-03-13 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200313_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ending_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='starting_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
