# Generated by Django 3.0.4 on 2020-03-15 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200313_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ending_time',
            field=models.TimeField(default=datetime.time(12, 30)),
        ),
    ]
