# Generated by Django 3.0.4 on 2020-03-15 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200316_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_of_booking',
            field=models.DateField(default=datetime.date(2020, 3, 16)),
        ),
    ]
